lib/verk.ex
lib/verk/queue_manager.ex
lib/verk/schedule_manager.ex
test/queue_manager_test.exs
test/schedule_manager_test.exs

It fixes https://github.com/edgurgel/verk/issues/4
We can check if `Redix.Error` happens instead of a normal connection error `(:closed)`

Fix script loading when Redix fail to evaluate

---

.travis.yml
mix.exs
mix.lock

We will need `:ets:update_counter/4` for the new `Verk.QueueStats` #soon
Elixir 1.1 was removed from Travis as it's failing with some crazy error: https://travis-ci.org/edgurgel/verk/jobs/103509836
Upgraded to timex `~> 1.0` as well

Move to erlang 18

---

lib/verk/retry_set.ex
lib/verk/workers_manager.ex
test/retry_set_test.exs
test/workers_manager_test.exs

* Add `Verk.RetrySet` to inspect the retry stored inside Redis.
* Change `WorkersManager.runnning_jobs` to list running jobs inside a queue returning a list of maps instead of raw tuples

Add some apis

---

lib/verk/queue_stats.ex
lib/verk/queue_stats_watcher.ex
lib/verk/supervisor.ex
test/queue_stats_test.exs
test/queue_stats_watcher_test.exs

`Verk.QueueStats` event handler will keep track of the work done by each queue:
* Running jobs counter
* Failed jobs counter
* Finished jobs counter
This can in the near future be used to store data related to amount of
jobs done inside Redis. It can from time to time increment the stats.
A Watcher was created to keep monitoring the handler as it's started by the GenEvent manager. More info: 
https://github.com/elixir-lang/elixir/blob/master/lib/logger/lib/logger/watcher.ex

Add queue stats

---

lib/verk/workers_manager.ex
test/workers_manager_test.exs

The monitored worker may die before the :done message is processed.
The manager will ignore a `:normal` reason of death as this is expected when the worker finishes its job.

Change WorkersManager handle_info to handle normal worker shutdown

---

README.md
lib/verk/queue_manager.ex
test/queue_manager_test.exs

Store too many retried jobs into a list of dead jobs.

Add dead jobs list

---

lib/verk/dead_set.ex
lib/verk/queue_manager.ex
lib/verk/retry_set.ex
test/dead_set_test.exs
test/queue_manager_test.exs
test/retry_set_test.exs

This PR replaces the list for a set to store the dead jobs. It also extracts the retry and dead set code to their modules making QueueManager just a user.

Use a set for dead jobs

---

lib/verk/queue_manager.ex
lib/verk/workers_manager.ex
test/queue_manager_test.exs
test/workers_manager_test.exs

This PR changes the way `QueueManager` dequeues jobs. Right now the queue manager will try to fetch as many jobs as the `WorkersManager` wants but this can be dangerous as if it takes more than 5 seconds to receive a response the call will timeout and these jobs will be not processed till `WorkersManager` starts again.
I also moved the decoding to the client side as it's an unnecessary computation happening on the `QueueManager` side that would add for the possible timeout.
Now it will dequeue a max of 100 jobs.

Change QueueManager dequeue to limit to 100 jobs

---

lib/verk/queue_stats.ex
lib/verk/queue_stats_counters.ex
lib/verk/stats.ex
test/queue_stats_test.exs
test/stats_test.exs

This PR is based on initial implementation provided by @iurifq (https://github.com/edgurgel/verk/pull/36)
It keeps the old API and persists the data to Redis each 10 seconds (is this a good default?)

Persist queue stats

---

lib/verk/workers_manager.ex
test/workers_manager_test.exs

The process may be gone when we are asking for its process info

Fix WorkersManager.inspect_worker when process is gone

---

lib/verk/worker.ex
lib/verk/workers_manager.ex
test/worker_test.exs
test/workers_manager_test.exs

It will always react to DOWN messages so there's no way a worker will be "lost"

Refactor workers manager

---

README.md
lib/verk.ex
lib/verk/log.ex
lib/verk/workers_manager.ex
test/verk_test.exs
test/workers_manager_test.exs

In #43 I've missed to update the code where Timex is used to match version 2.x as explained in [Timex Migration steps](https://github.com/bitwalker/timex#migration-steps-1x---2x).
Some of it is just nice to have, but other might be breaking things, like for example `Date.now` is returning date instead of datetime:
```
iex(2)> Timex.Date.now
#<Date(2016-04-05)>
iex(3)> Timex.DateTime.now
#<DateTime(2016-04-05T10:59:29Z)>
```

Update usage of Timex to comply with Timex 2.x requirements.

---

lib/verk/job.ex
lib/verk/poison_version.ex
mix.exs

problem: 
- some projects already use poison 2.0 (or 2.1), verk installation does not work there
solution: 
- also allow poison 2.0 by relaxing dependency
```
{ :poison, "~> 1.5 or ~> 2.0"},
```

also allow poison 2.0 as dep

---

lib/verk/queue_stats.ex
lib/verk/queue_stats_counters.ex
lib/verk/workers_manager.ex
test/queue_stats_test.exs
test/workers_manager_test.exs

This is necessary so that if the WorkersManager restarts the started counter to 0 as no worker survived to fail/finish the previous running jobs.
There's also the nice side-effect of always registering the queue to QueueStats even if no job ever runs for this queue. Previously it would register just if at least 1 job ran.

Reset started counter

---

lib/verk/log.ex
test/log_test.exs

This as an attempt at closing https://github.com/edgurgel/verk/issues/34, but `Timex.DateTime` only has granularity to milliseconds ([link](https://github.com/bitwalker/timex/blob/master/lib/datetime/datetime.ex#L25-L33)) and `Timex.Diff` doesn't allow you to specify milliseconds ([link](https://github.com/bitwalker/timex/blob/fcacaffa5ca015e807af87b5d211912bce0587d9/lib/comparable/comparable.ex#L15-L25)) so I ended up manually subtracting the DateTime milliseconds from each other if the seconds difference is zero.
For units smaller than milliseconds, I think it would require using `Timex.Time`, which would require more work and potentially break compatibility?
Thank you for making verk :)

show job time down to milliseconds

---

config/config.exs
lib/verk/queue_supervisor.ex
lib/verk/workers_manager.ex
test/workers_manager_test.exs

My initial attempt at closing https://github.com/edgurgel/verk/issues/41
I wasn't sure if the configuration should happen in the WorkersManager module or if it should be passed in from the supervisor as I did.  Credo is also not happy that the number of args is up to 6 for `Verk.WorkersManager.start_link`.

Configurable workers manager timeout

---

lib/verk/workers_manager.ex
test/workers_manager_test.exs

To hopefully close https://github.com/edgurgel/verk/issues/38
I wasn't sure if there was a preferred way range for the random timeout, but this PR currently has it between 1x-2x as long as the configured timeout.
This makes testing a bit goofy, and there is probably a better way to handle it.

random timeout

---

lib/verk/queue_manager.ex
test/queue_manager_test.exs

I've had some pretty bad crashes from this (bringing down the entire verk application), and the root cause is from `System.stracktrace` [here](https://github.com/edgurgel/verk/blob/master/lib/verk/worker.ex#L40) returning a stacktrace like `{GenServer, :call, [:my_named_process, \"1\", 5000]}`.
Verk eventually attempts to format with `Exception.format_stacktrace/1` [here](https://github.com/edgurgel/verk/blob/master/lib/verk/queue_manager.ex#L134), which doesn't work since that calls `Enum.map_join`, and a tuple isn't Enumerable.
A contrived example of a worker that causes this:
```elixir
defmodule Verk.TestWorker do
def perform(key_or_keys) do
GenServer.call(:my_named_process, "1")
end
end
```
I added a test that will fail without my changes:
```
1) test call retry on a job with non-enum …
```

Fix bad stacktrace formatting

---

lib/verk/retry_set.ex
lib/verk/sorted_set.ex
test/retry_set_test.exs
test/sorted_set_test.exs

If the job or the sorted set does not exist a `boolean` will say:
* `true` if the delete succeeded
* `false` if the delete failed
Most of the time it doesn't really mater if you failed or not as it will just be a no-op.

Refactor SortedSet.{clear, delete_job} to return {:ok, boolean}

---

lib/verk/workers_manager.ex
test/workers_manager_test.exs

To fix https://github.com/edgurgel/verk/issues/59

use :poolboy.status to get free workers

---

README.md
lib/verk.ex
mix.exs

All the users will need to change their supervision trees to add `Verk.Supervisor`.
I'm glad we are not on 1.0.0 yet :)
It closes https://github.com/edgurgel/verk/issues/58

Change Verk application to not start Verk.Supervisor

---

lib/verk/worker.ex

The apply modules must already be there~

String.to_atom/1 may cause atom exhaust in worker's process

---

lib/verk/worker.ex
test/worker_test.exs

if just use String.to_existing_atom/1
```
%Verk.Job{class: ModuleAtom.Name}
will be change to 
"Elixir.Elixir.ModuleAtom.Name" |> String.to_existing_atom
```
so we better use Module.safe_concat/1 to add Elixir prefix 
：）
Thanks for the great project~

Find class module by Module.safe_concat/1

---

README.md
lib/verk.ex
lib/verk/job.ex
lib/verk/queue_manager.ex
test/job_test.exs
test/queue_manager_test.exs
test/verk_test.exs

For #81 
Allows for configuring a global max_retry_count with:
```elixir
config :verk,
max_retry_count: 1
```
Or when the job is added:
```elixir
Verk.enqueue(%Verk.Job{ queue: "queue", jid: "job_id", class: "TestWorker",
args: 123, max_retry_count: 10 })
```
But otherwise continues to default to 25

Configurable max_retry_count

---

lib/verk/dead_set.ex

Allows user's to configure the size of the Redis set that tracks "dead" jobs. In certain situations ("must run at least once" jobs) users may want to configure this variable quite high in order to potentiall re-enqueue critical jobs.

Change DeadSet max set size to be configurable

---

lib/verk/queue_manager.ex

This constant doesn't seem to be used anywhere.

Remove unused @max_dead constant in queue_manager.ex

---

lib/verk/stats.ex
test/stats_test.exs

Also see: https://github.com/edgurgel/verk_web/pull/27
This PR adds an additional method to `lib/verk/stats.ex` that returns total processed/failed job counts for every queue in the format:
```
%{<queue> => %{total_finished: <# finished>, total_failed: <# failed>}, ...}
```

Add method for persisted queue stats

---

lib/verk/retry_set.ex
lib/verk/sorted_set.ex
test/retry_set_test.exs
test/sorted_set_test.exs

This additional method allows for listing jobs by their precedence within a Redis set. This can be useful for determining when a job will next be attempted or when a dead job was declared dead, among other possible uses.

Add {SortedSet,RetrySet}.range_with_score/3

---

lib/verk/job.ex
lib/verk/queue_manager.ex
lib/verk/workers_manager.ex
test/job_test.exs
test/queue_manager_test.exs
test/workers_manager_test.exs

This is a first pass at addressing https://github.com/edgurgel/verk/issues/89. I was initially unsure of how to skip jobs because `QueueManager.dequeue`will have already moved them to the `inprogress` queue. But calling `QueueManager.ack` will remove it.
It might be cleaner to add a new handler to `QueueManager` that does the same thing as `:ack` but is explicitly used for removal (whereas using `:ack` seems to imply removal of a successfully completed job).
It is pretty difficult to add a test for this as enqueuing jobs from Verk uses Poison encoding and thus the interoperability problem I am running into cannot be recreated easily.

Rescue JSON decoding errors rather than killing WorkerManager

---

README.md

I was just reading over the docs and realized I made a typo here. We need to add the GenServer to the supervision tree not the handler itself.

Typo in error tracking docs supervision tree

---

README.md
lib/verk/log.ex

This PR addresses https://github.com/edgurgel/verk/issues/66 using the `Logger.log/3` method discussed in that issue.
This has the tradeoff of being less verbose but not taking advantage of compile time optimization of logging calls that would happen using a method such as the one proposed in my earlier comment https://github.com/edgurgel/verk/issues/66#issuecomment-260406840.

Configure log levels

---

lib/verk/retry_set.ex
lib/verk/sorted_set.ex
priv/requeue_job_now.lua
test/redis_scripts_test.exs
test/retry_set_test.exs
test/sorted_set_test.exs

This PR is a first pass at adding the necessary Verk changes required to support on-demand job retrying for jobs in the retry queue (see: https://github.com/edgurgel/verk_web/issues/11).
The implementation is fairly self-explanatory, it primarily follows the patterns used in [enqueue_retriable_job.lua](https://github.com/edgurgel/verk/blob/master/priv/enqueue_retriable_job.lua) as well as [SortedSet.delete](https://github.com/edgurgel/verk/blob/c252802a095efe786c48299898b1f249d8108064/lib/verk/sorted_set.ex#L109-L114).
I expect that the change for https://github.com/edgurgel/verk_web/issues/11 will simply be the addition of another button (as for "Delete") that calls `RetrySet.requeue_job` in the controller ([as for "Delete"](https://github.com/edgurgel/verk_web/blob/bc0d71888944b1490e49a5 …

Add [SortedSet,RetrySet].requeue_job for on-demand job retries

---

lib/verk/queue_stats.ex
lib/verk/queue_stats_counters.ex
test/queue_stats_test.exs

Searching for a prefix helps a lot when you have lots of different queues. 
This is useful if you have lots of different queues. 
The Verk Web part is coming soon 🔜

Change Verk.QueueStats.all to search for a prefix

---

lib/verk/queue_stats.ex
test/queue_stats_test.exs

It needs to have a default handle_info otherwise any other GenEvent message can raise exceptions.

Fix QueueStats GenEvent

---

lib/verk.ex
lib/verk/queue_manager.ex
lib/verk/queue_stats.ex
lib/verk/queue_stats_counters.ex
lib/verk/schedule_manager.ex
lib/verk/worker.ex
lib/verk/workers_manager.ex
mix.exs

There are a couple Erlang 19 warnings as well, but I was less sure about changing them:
```
warning: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1
lib/verk.ex:92
warning: random:uniform/1: the 'random' module is deprecated; use the 'rand' module instead
lib/verk/retry_set.ex:38
```

fix compile warnings for Elixir 1.4

---

README.md
lib/verk/dead_set.ex
lib/verk/job.ex
lib/verk/log.ex
lib/verk/queue_manager.ex
lib/verk/schedule_manager.ex
lib/verk/supervisor.ex
lib/verk/workers_manager.ex
mix.exs
mix.lock
test/dead_set_test.exs
test/queue_manager_test.exs
test/queue_stats_test.exs
test/queue_test.exs
test/redis_scripts_test.exs
test/schedule_manager_test.exs
test/sorted_set_test.exs
test/stats_test.exs
test/workers_manager_test.exs

Add supports for env config at release runtime using Confex.
I did not bother emulating fetch and fetch! for `redis_url` as I dont think this adds much more safety, it will simply error differently . We could probably add one check (in the supervisor ?) that would raise if `redis_url` is not defined.

Use Confex to support env config at release runtime

---

lib/verk.ex
lib/verk/manager.ex
lib/verk/manager_supervisor.ex
lib/verk/queue_supervisor.ex
lib/verk/supervisor.ex
mix.exs
test/manager_supervisor_test.exs
test/manager_test.exs
test/queue_supervisor_test.exs
test/supervisor_test.exs
test/verk_test.exs

This is a prerequisite to finish the work started on #127 
The PR adds `Verk.Manager` to control the state of queues. When a queue is added or removed, `Verk.Manager` will be the single place of control.
When we finally implement pause/resume, `Verk.Manager` will provide the state (running or paused). So if any queue supervisor restarts, the Manager will provide the initial state.

Verk manager

---

mix.exs
mix.lock

GenStage has a new release out, I am also using Quantum and that requires the latest release.

Bump gen_stage to 0.12.2

---

lib/verk/job.ex

Poison 3.0.0 introduces a change to the return tuple that breaks the handling added in #91. The method signature change is documented in: devinus/poison#149. It seems that this signature might be changed back in Poison 4.0.0.
This change allows Verk to support Poison 3.0.0 and not crash on invalid jobs.
See https://github.com/edgurgel/verk/issues/144

Handle Poison 3.X decode error tuples

---

lib/verk/retry_set.ex
test/retry_set_test.exs

It will rescue if the Worker module name does not exist
It fixes #151

Change RetrySet to calculate next retry safely

---

lib/verk/job.ex
test/job_test.exs

When decoding payload to create a job replace empty map for args with
empty array.

Fix #149 - Replace map with array for job with no args.

---

.travis.yml
config/config.exs
lib/verk/event_producer.ex
lib/verk/queues_drainer.ex
lib/verk/supervisor.ex
test/integration/.gitignore
test/integration/README.md
test/integration/config/config.exs
test/integration/lib/integration.ex
test/integration/lib/integration/application.ex
test/integration/lib/integration/no_op_worker.ex
test/integration/lib/integration/sleep_worker.ex
test/integration/mix.exs
test/integration/mix.lock
test/integration/test/integration_test.exs
test/integration/test/test_helper.exs
test/queues_drainer_test.exs
test/supervisor_test.exs
test/test_helper.exs

This PR changes the way `Verk` will shutdown. It uses a `GenStage` consumer to watch for all the queues that should be paused. Waiting a max of `shutdown_timeout`
It fixes https://github.com/edgurgel/verk/issues/96
cc/ @krasio

Gracefully pause queues before shutting down

---

README.md

- Described the pitfalls of not using `node_id` properly.
- Simplified Heroku config example to emphasize the important part.
- Added warning about duplicate dyno environment variables in Heroku.
- Added Kubernetes section.

Added Deployment section to README

---

mix.exs
mix.lock

The documentation suggests that you do the following:
```elixir
config :verk,
queues: {:system, {MyApp.Env, :verk_queues, []}, "VERK_DISABLED"}
defmodule MyApp.Env do
def verk_queues("true"), do: []
def verk_queues(_), do: [default: 25, priority: 10]
end
```
Unfortunately this MFA style configuration was only introduced in confex 3.3. I have bumped the version of confex to `~> 3.3.0` so the documentation is correct. Is that any reason we can't bump to `~> 3.3`?

Bump confex version to support documented config

---

README.md
lib/verk/dead_set.ex
lib/verk/job.ex
test/dead_set_test.exs
test/job_test.exs
test/verk_test.exs

This PR aims to solve issues #170 and #174.
Both `max_retry_count` and `max_dead_jobs` are now over writable by the client as they are no longer associated with a constant, thus evaluated on runtime.
Also this PR updates the documentation, using `max_dead_jobs` on the readme example configuration and explaining both these configurations on the modules they are used at.

Over writable configs

---

lib/verk/queues_drainer.ex
lib/verk/sorted_set.ex

While compiling, I had these deprecations:
```
Compiling 24 files (.ex)
warning: variable "reason" is unused
lib/verk/queues_drainer.ex:49
warning: variable "shutdown_timeout" is unused
lib/verk/queues_drainer.ex:49
warning: Enum.chunk/2 is deprecated. Use Enum.chunk_every/2 instead
lib/verk/sorted_set.ex:82
```
I realize _chunk_ is for older OTP versions. I assume the project doesn't want to deprecate until actually necessary?

fix(elixir): Fix unused vars, chunk_every

---

lib/verk/in_progress_queue.ex
lib/verk/log.ex
lib/verk/manager.ex
lib/verk/node.ex
lib/verk/node/manager.ex
lib/verk/queue_manager.ex
lib/verk/queue_supervisor.ex
lib/verk/supervisor.ex
test/in_progress_queue_test.exs
test/manager_test.exs
test/node/manager_test.exs
test/node_test.exs
test/queue_manager_test.exs
test/supervisor_test.exs

Hey team here is my first stab at solving this issue: https://github.com/edgurgel/verk/pull/159/files
The idea is:
(frequency) = 60 seconds ?
On starts Each node generates a new id (We can check if it's actually new by the result of SADD)
SADD nodes node_id
PSETEX verk:node:#{node_id} 2 * frequency alive]
Each time a node starts working on a queue the queue name is added to "node:queues" set;
Each time a node stops working on a queue the queue name is removed from "node:queues" set;
Each frequency seconds we set the node key to expire in 2 * frequency
PSETEX verk:node:#{node_id} 2 * frequency alive]
Also check for all the keys of all nodes. If the key expired it means that this node is dead.
To restore we go through all the running queues of that node and enqueue them from progress back …

Resilient Verk - Fix scaling up and down

---

lib/verk/manager.ex
lib/verk/node.ex
lib/verk/node/manager.ex
lib/verk/queue_manager.ex
test/integration/test/integration_test.exs
test/manager_test.exs
test/node/manager_test.exs
test/node_test.exs
test/queue_manager_test.exs

Here are some changes I made from the original PR #159 
* Change so that `QueueManager` maintains `verk_nodes` and `verk:node:#{node_id}:queues` up-to-date. It avoids possible de-synchronization between Redis and local state of the Verk node. The main idea behind this changes is: "If any job is added to the `inprogress` list, this node and this queue must be tracked so that other nodes can rescue their failure if it happens."
`QueueManager` will conditionally maintain these data structures if `generate_node_id` is true.
* Change `Node.Manager` to not crash if `heartbeat` failed.

Resilient verk improvements

---

lib/verk/supervisor.ex

Elixir v1.5 allows child specifications, which specify how a child process is supervised, to be defined in modules.
```
children = [
MyApp.Repo,
MyApp.Endpoint,
Verk.Supervisor
]
Supervisor.start_link(children, strategy: :one_for_one)
```

Change Verk.Supervisor to support treamlined child specs

---

mix.exs

Removes the `.0` version requirement so that confex works with versions later than `3.3`.

Relax Confex Version - closes #189

---

lib/verk/job.ex
test/job_test.exs

It should only care about `Verk.Job` struct keys discarding any unknown keys.
This is a safer implementation for users that schedule jobs to Verk
using ruby `Sidekiq::Client`.
A recent version of `newrelic_rpm` gem is injecting code into Sidekiq
jobs for some sort of tracing/inspection making jobs scheduled with
`Sidekiq::Client` invalid to Verk as they contain an unknown job key.

Fix Verk.Job decode/1
