edgurgel/verk

- README.md
- lib/verk/events.ex
- lib/verk/queue_manager.ex
- lib/verk/supervisor.ex
- lib/verk/worker.ex
- lib/verk/workers_manager.ex
- mix.exs
- test/queue_manager_test.exs
- test/worker_test.exs
- test/workers_manager_test.exs
It closes https://github.com/edgurgel/verk/issues/3
> Add events

- lib/verk.ex
- lib/verk/retry_set.ex
- lib/verk/supervisor.ex
- test/retry_set_test.exs
- test/verk_test.exs
* Change Verk.enqueue to use the general purpose redis connection
* Change Verk.RetrySet to use the general purpose redis connection
> Add general purpose redis process

- lib/verk/retry_set.ex
- test/retry_set_test.exs
It will accept the job with the original json or the json itself
> Add Verk.RetrySet.delete_job/1

- lib/verk/queue.ex
- test/queue_test.exs
Similar implementation from Verk.RetrySet
> Add Verk.Queue to inspect a queue

- lib/verk/job.ex
- lib/verk/queue_manager.ex
- lib/verk/workers_manager.ex
- test/queue_manager_test.exs
- test/workers_manager_test.exs
This will be useful to show more information when retries is inspected
It closes https://github.com/edgurgel/verk/issues/16
> Add retried at and backtrace

- lib/verk/retry_set.ex
- lib/verk/schedule_manager.ex
- lib/verk/sorted_set.ex
- test/retry_set_test.exs
- test/sorted_set_test.exs
The default value for `RetrySet` is the `Verk.Redis` connection
> Add redis connection argument to {Retry, Sort}Set functions

- lib/verk.ex
- test/verk_test.exs
The default value is Verk.Redis
This is useful if one wants to use another connection or another instance of Redis (possible another system like Sidekiq, Resque or other Verk)
> Add optional parameter to Verk.{enqueue, schedule}

- lib/verk.ex
* Unify the jid generation on Verk.{enqueue, schedule}
* Remove the dot as dots are used for too many different things out there in the internet
> Simplify automatic jid generation

- lib/verk/workers_manager.ex
- test/workers_manager_test.exs
If an exit happens the `DOWN` message will have only a reason.
These are the 3 possible cases:
* Erlang error -> `{reason, stack}`
* Erlang throw -> `{reason, stack}`
* Erlang exit -> `reason`
Now we keep track of all of the cases + `:normal`: reason which is expected to happen after the job is finished.
> Add WorkersManager.handle_info DOWN without stacktrace clause

- lib/verk/workers_manager.ex
- test/workers_manager_test.exs
It provides information about a giving worker based on the job id
> Add WorkersManager.inspect_worker/2

- lib/verk/dead_set.ex
- lib/verk/dsl.ex
- lib/verk/queue.ex
- lib/verk/retry_set.ex
- lib/verk/sorted_set.ex
- test/dead_set_test.exs
- test/dsl_test.exs
- test/queue_test.exs
- test/retry_set_test.exs
- test/sorted_set_test.exs
These modules now offer pair of bang and non-bang variants for their
public functions.
Add macro to ease creating bang variants of functions.
Closes #49.
> Update Queue, SortedSet, RetrySet and DeadSet modules interface.

- lib/verk/worker.ex
- lib/verk/workers_manager.ex
- test/worker_test.exs
- test/workers_manager_test.exs
> Add worker metadata

- lib/verk/queue.ex
- lib/verk/retry_set.ex
- lib/verk/sorted_set.ex
- test/queue_test.exs
Update `Queue.clear` and `Queue.delete_job` to returns booleans as well. Thanks again @krasio !
I also updated the docs to reflect the changes applied.
> Refactor queue clear delete job

- lib/verk/workers_manager.ex
- test/workers_manager_test.exs
There's a chance that poolboy didn't notice that a worker finished/falied. 
We should enforce that poolboy will checkin before status is called through the `:timeout` message.
The checkin will happen when a DOWN, done or failed message arrives. The worker will be registered back to poolboy. This naturally happens because it's also monitored by poolboy but poolboy may not receive the message before a `status` is issued.
> Ensure WorkersManager checks in workers back

- .travis.yml
- test/queue_manager_test.exs
Related to https://github.com/edgurgel/verk/pull/75
> Add Elixir 1.3.2 to .travis.yml

- README.md
Updates README to address https://github.com/edgurgel/verk/issues/83.
> Fixes #83, update README feature set

- README.md
I found the README to be just a little too vague and I felt a bit lost setting up my new event handler. Not sure if this is the best way to implement error tracking, but it worked for me.
> Update README, error tracking section

- lib/verk/queue_manager.ex
- lib/verk/workers_manager.ex
- priv/lpop_rpush_src_dest.lua
- test/queue_manager_test.exs
- test/redis_scripts_test.exs
- test/workers_manager_test.exs
It will fetch a maximum of 1000 at a time when enqueue jobs from the inprogress list
It closes https://github.com/edgurgel/verk/issues/35
> Change lpop_rpush_src_dest to work in batches

- README.md
- config/config.exs
- lib/verk/event_producer.ex
- lib/verk/queue_stats.ex
- lib/verk/supervisor.ex
- lib/verk/workers_manager.ex
- mix.exs
- test/queue_stats_test.exs
- test/supervisor_test.exs
- test/workers_manager_test.exs
Removing GenEvent and using GenStage to produce events. Still unsure if we should discard the demand and simply broadcast... 🤔
> Remove GenEvent

- lib/verk/events.ex
- lib/verk/job.ex
- lib/verk/workers_manager.ex
- test/workers_manager_test.exs
> Add started at & Job finished at

- lib/verk/workers_manager.ex
- test/dead_set_test.exs
- test/dsl_test.exs
- test/log_test.exs
- test/queue_manager_test.exs
- test/queue_stats_test.exs
- test/retry_set_test.exs
- test/schedule_manager_test.exs
- test/sorted_set_test.exs
- test/verk_test.exs
- test/worker_test.exs
- test/workers_manager_test.exs
> Cleaning up parentheses warnings in Elixir 1.4

- mix.exs
> Allow poison 3

- README.md
- lib/verk/retry_set.ex
- test/retry_set_test.exs
> Add custom retry time delay

- lib/verk/queue_manager.ex
fixes #147 
Turns out solution is much easier, credo is already passing:
```
✗ mix credo --strict
Checking 23 source files ...
Please report incorrect results: https://github.com/rrrene/credo/issues
Analysis took 1 second (0.02s to load, 0.9s running checks)
250 mods/funs, found no issues.
```
> Remove @lint statement

- .travis.yml
- test/integration/lib/integration.ex
- test/integration/test/integration_test.exs
- test/supervisor_test.exs
* Exclude integration test when running Verk tests.
* Add drainer to supervisor_test.
* Do not run doctests for the integration app.
> Fix TravisCI build.

- lib/verk/log.ex
- lib/verk/schedule_manager.ex
- lib/verk/time.ex
- mix.exs
- mix.lock
- test/log_test.exs
- test/time_test.exs
- test/verk_test.exs
Hey Ed!
Heres the PR. All tests green on my 1.8 Elixir, but I haven't tested earlier versions. I'll shut #181 in the meantime.
Thanks for making (and looking after) verk! :1st_place_medal:
> Fixes Deprecation warnings for Elixir 1.8

- mix.exs
- mix.lock
GenStage it's now at 1.0, because this dependency I need to update Verk's version. 
Thanks.
> Update gen stage version to 1.0
